version: 3

services:
  #spring boot settings
  springboot:
    image: "library_book_backend:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "library_book_backend"
    depends_on:
      - postgresql_bd
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_bd:5432/library-book
      - SPRING_DATASOURCE_USERNAME=spacecodee
      - SPRING_DATASOURCE_PASSWORD=spacecodee
    ports:
      - "8080:8080"

  postgresql_bd:
    image: "postgres:latest"
    container_name: "postgresql_bd"
    environment:
      - POSTGRES_PASSWORD=spacecodee
      - POSTGRES_USER=spacecodee
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data